#!/usr/bin/env bash

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config click_to_focus       true


bspc rule -a Firefox     desktop=^8
bspc rule -a qutebrowser desktop=^7
bspc rule -a feh                    floating=on
bspc rule -a Mplayer                floating=on
bspc rule -a VirtualBox             floating=on
bspc rule -a pavucontrol            floating=on
bspc rule -a nitrogen               floating=on center=true

${HOME}/.config/bspwm/panel
